### ISSUE TITLE
Perform some form of batching of Aave deposits

### ISSUE THREAD

**Issue by TomAFrench** [Good-Ghosting/goodghosting-smart-contracts#54]
I'm mostly thinking out loud here but the way I see it is the majority of the gas costs of GoodGhosting is through the direct interactions with the Aave contracts in order to deposit. If there's 30 people all depositing $20-30 a month then that's a lot of gas spent for relative to the amount of funds deposited.

I think there needs to be some thinking on how to incentivise a user to pay the additional gas costs to deposit everyone else's funds into Aave and guarantee that funds from a given round will be deposited promptly. Otherwise we get into a situation where the game ends and there's hardly any interest because everybody is hoping that everybody else will pay the gas to deposit.

Maybe there could be a bounty for players who choose to deposit their funds (and any DAI sitting on the goodGhosting contract) into Aave. Users can also choose to make their payment to the GoodGhosting contract without depositing into Aave (leaving their DAI sitting on the contract earning no interest) but this increases the bounty by ~$0.5 or so. It should only be a couple of deposits before someone will make more from the bounty than what they pay in increased gas.

It's an open question on how this bounty should be paid for. Out of the general prize pool? Directly by the users who don't deposit their funds themselves?

**Comment by Deepcryptodive** [comment]
Hello Tom, 

Indeed that is a valid point, that was talked about internally before, but could use improvements. The minting of aDAI is quite expensive.

The current thinking is: we allow users to deposit plain DAI into the GoodGhosting contract, and then make 1 pooled deposit into Aave at the start of a each new game segment (e.g. weekly) to obtain aDAI. 

To improve upon this, we could make use of the[ `permit` function](https://github.com/makerdao/developerguides/blob/master/dai/how-to-use-permit-function/how-to-use-permit-function.md) in the DAI token contract, which is a signature-based approval function. Using this, users do not have to pay any gas for their DAI to be moved into the GoodGhosting contract, they just need to sign a message with Metamask. This gives the GoodGhosting contract permission to move their funds. This way, the deposits of all players DAI could be batched into one transaction, as long as each player holds enough DAI in their wallet.

The question remains who pays for the deposit transaction costs. Initially we could cover the cost ourselves (with the funds from the Gitcoin/Aave grant), or it could be taken from the general prize pool.

I like the 'bounty' idea too, so there are no moments while funds are not gaining any interest. But that might only make sense in big pools and/or at high interest rate levels.  At current Aave APY rates, there is only ~$0.5 gained in daily interest on a $1500 deposit (~30 players at 50 DAI). It only makes sense if the gained interest, is more than the the tx cost. 

_Tx costs at 100 Gwei:_
Minting aDAI = ~$7.5
Redeeming aDAI = ~$7.5
Transfering DAI to another address = ~$1.2
Transfering aDAI to another address = ~$18


**Other ideas to minimize gas costs:**
- use https://gelato.network/ to define conditions when a transactions should execute (i.e. trigger the Aave deposit when gas prices are low).
- use https://disperse.app/ for send out the funds at the end of the game (batch-send ERC20 tokens in a gas-efficient way)
- plug into Aave's L2 whenever it launches
- use xDAI for deposits into the GoodGhosting contract instead of DAI

**Comment by TomAFrench** [comment]
I like the idea of using `permit` for batched deposits (although it would require a little bit of infra to accumulate those signatures), especially with something like disperse.app for distribution as at that point there's no need for any users to have gas at any stage. Ideally someone can use Transak to get DAI in Argent or something and then start saving.

Yeah, I haven't done any maths on what the required APY/deposit would need to be for a bounty to be sustainable. Agreed on covering gas with Gitcoin/Aave for now. You're relatively flexible seeing as you're redeploying for each game so it'll be easy to make it easier to incentivise others to take on that role.

**Comment by fodisi** [comment]
Addressed in PR #65 .
